### ISSUE TITLE
Mandatory unused $data in MediaObject::getImageSrc();

### ISSUE THREAD

**Issue by jhuet** [dereuromark/MediaEmbed#10]
Hello there,

Is (was?) there any purpose for the `$data` mandatory parameter of the [`MediaObject::getImageSrc($data);`](https://github.com/dereuromark/MediaEmbed/blob/master/src/MediaEmbed/Object/MediaObject.php#L429) method ?

**Comment by dereuromark** [comment]
No I think that can be removed. You can make a PR for it?
