### ISSUE TITLE
Embed links should use HTTPS where possible

### ISSUE THREAD

**Issue by BrandonSurowiec** [dereuromark/MediaEmbed#14]
If you embed an iframe with an HTTP link on a secure HTTPS page the SSL icon becomes insecure and throws warnings about insecure content.

**Comment by dereuromark** [comment]
Any idea what to do here?

**Comment by michilehr** [comment]
iframes and images can be used protocol relative when ssl is available. I will commit this for youtube, facebook and vimeo in the next minutes.

**Comment by michilehr** [comment]
All others must be checked if they were available via SSL @BrandonSurowiec
