### ISSUE TITLE
Facebook embed not working

### ISSUE THREAD

**Issue by 411x** [dereuromark/MediaEmbed#18]
Message in the FB player :  
> href should represent a valid URL  

```
function getEmbed( $id, $host ) {  

        $MediaEmbed = new MediaEmbed();  

        $MediaObject = $MediaEmbed->parseId($id, $host);  

        if (!$MediaObject) {  
            return '';  
        }  
        return $MediaObject->getEmbedCode();  
}
```

I call the function this way
getEmbed($embed->id(), $embed->slug());  

(and I checked, the slug and id are good)
  
And this is the embed code I got

`<iframe src="https://www.facebook.com/plugins/video.php?href=$1&show_text=0&amp;wmode=transparent" type="" width="480" height="295" frameborder="0" allowfullscreen class="embed-responsive-item" data-html5-parameter></iframe>`

  
MediaEmbed->parseUrl is working without a problem with facebook.

**Comment by dereuromark** [comment]
So what is your expectation here? Do you know a fix?

**Comment by 411x** [comment]
I naively expected to have a working player that works with just "facebook" and the id.
But i get it, you can't constuct the entire "href" url with only these two elements. We need the profile slug also..
  
I have two dirty cheap fix (the second one seems the better):  

1. replace in stubs.php

`'iframe-player' => 'https://www.facebook.com/plugins/video.php?href=$1&show_text=0',`

by

`'iframe-player' => 'https://www.facebook.com/video/embed?video_id=$2',`

but.. this url (working to this day) is deprecated..  
[https://developers.facebook.com/docs/plugins/embedded-video-player#faq](https://developers.facebook.com/docs/plugins/embedded-video-player#faq)

> If you use the embed_html property's value, your video player will:
> 
> * Not work on mobile devices and tablets
> * Not contain any additional information like views, video title, etc.

2. replace the unknown profile slug by "facebook" and it's working perfectly (like, share & co) as if it was
the real profile slug.

`'iframe-player' => 'https://www.facebook.com/plugins/video.php?href=https%3A%2F%2Fwww.facebook.com%2Ffacebook%2Fvideos%2F$2%2F&show_text=0',`

So, my fix to this day is the second one.

**Comment by dereuromark** [comment]
Can you please make a PR with the suggest fix?

**Comment by dereuromark** [comment]
Can you confirm that https://github.com/dereuromark/MediaEmbed/pull/20 resolves this?

**Comment by Erwane** [comment]
merge #23 solve that. Could you bump the version please ?

Thanks.

**Comment by dereuromark** [comment]
I dont quite get why we changed it to $2, and now back to $1.
```
'https://www.facebook.com/[0-9a-z-_.]+/videos/([0-9]+)/',
'https://www.facebook.com/[0-9a-zA-Z-_.]+/videos/(?:vb.\d+)/(\d+)/',
'https://www.facebook.com/[0-9a-zA-Z-_.]+/videos/(?:vl.\d+)/(\d+)/'
```

Are all 3 still working?

**Comment by Erwane** [comment]
Yes it's working (in november).
Because Facebook require the full url now, not only the video Id
