### ISSUE TITLE
Composer is not not installing dereuromark/media-embed

### ISSUE THREAD

**Issue by alamgircsejnu** [dereuromark/MediaEmbed#21]
When I run the command you suggested "composer require dereuromark/media-embed" it's showing following error.

_**Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dereuromark/media-embed No version set (parsed as 1.0.0) is satisfiable by dereuromark/media-embed[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.**_

How can I resolve this?

**Comment by dimvic** [comment]
In order to get past this you will need to add to your project's composer.json
```
  "minimum-stability": "dev"
```

preferably together with
```
  "prefer-stable": true
```

and be careful on how you define your requirements so that you don't end up installing dev versions that break

**Comment by dereuromark** [comment]
why is this needed?

**Comment by alamgircsejnu** [comment]
For streaming video from google photo. But I found another script. Thank you for your response.

**Comment by dereuromark** [comment]
i was talking about min stab
