### ISSUE TITLE
DailyMotion Videos don't work

### ISSUE THREAD

**Issue by netstyler** [dereuromark/MediaEmbed#32]
DailyMotion videos do not work anymore.

Example Url's: 

https://dai.ly/x6xaldv
https://www.dailymotion.com/video/x6x4shm

How to reproduce:
https://sandbox.dereuromark.de/sandbox/media-embed
Entering them there gives an error in parsing URL.

**Comment by dereuromark** [comment]
Amy idea how to fix?

**Comment by netstyler** [comment]
@dereuromark 
Check out my PR. hope is cool. ;)
